from tiling_objects import Tile
import numpy as np

TILES = [
    Tile("t1",
        "#fc0303",
            np.array([
            [
                [0,1],
                [1,1],
                [0,1]
            ],
            [
                [0,1],
                [0,0],
                [0,0]
            ]
        ]),
    ),
    Tile("t2",
          "#fc5a03",
          np.array([
            [
                [1,1],
                [0,1],
                [0,1]
            ],
            [
                [0,0],
                [0,0],
                [0,1]
            ]
        ]),
    ),
    Tile("t3",
         "#fc9003", 
         np.array([
            [
                [1,1],
                [1,0]
            ],
            [
                [0,1],
                [0,0]
            ]
        ]),
    ),
    Tile("t4",
         "#fcf003",
          np.array([
            [
                [1,1],
                [0,1],
                [1,1]
            ]
        ]),
    ),
    Tile("t5",
         "#5efc03",
          np.array([
            [
                [0,1],
                [0,1],
                [1,1]
            ],
            [
                [0,0],
                [0,0],
                [1,0]
            ]
        ]),
    ),
    Tile("t6",
         "#03fc56",
          np.array([
            [
                [1,0],
                [1,1],
                [0,1]
            ],
            [
                [1,0],
                [0,0],
                [0,0]
            ]
        ]),
    ),
    Tile("t7",
         "#03fcba",
          np.array([
            [
                [0,1],
                [1,1],
                [1,1]
            ]
        ]),
    ),
    Tile("t8",
         "#03cafc",
          np.array([
            [
                [0,1],
                [1,1]
            ]
        ]),
    ),
    Tile("t9",
         "#0367fc",
          np.array([
            [
                [1,1],
                [1,1]
            ],
            [
                [0,1],
                [0,0]
            ]
        ]),
    ),
    Tile("t10",
         "#030bfc",
          np.array([
            [
                [1,1],
                [0,1]
            ],
            [
                [1,0],
                [0,0]
            ]
        ]),
    ),
    Tile("t11",
         "#6703fc",
          np.array([
            [
                [0,1],
                [0,1],
                [1,1]
            ],
            [
                [0,1],
                [0,0],
                [0,0]
            ]
        ]),
    ),
    Tile("t12",
         "#ba03fc",
          np.array([
            [
                [1,0],
                [1,1],
                [0,1]
            ]
        ]),
    ),
    Tile("t13",
         "#fc03d2",
          np.array([
            [
                [0,1],
                [1,1],
                [1,0]
            ],
            [
                [0,1],
                [0,0],
                [0,0]
            ]
        ]),
    ),
    Tile("t14",
         "#fc035e",
          np.array([
            [
                [1,1],
                [0,1],
                [0,1]
            ],
            [
                [1,0],
                [0,0],
                [0,0]
            ]
        ]),
    ),
    Tile("t15",
         "#fca503",
          np.array([
            [
                [0,1],
                [1,1],
                [0,1]
            ]
        ]),
    ),
    Tile("t16",
         "#fcba03",
          np.array([
            [
                [0,1],
                [0,1],
                [1,1]
            ]
        ]),
    ),   
]

def get_tiles_by_name(names:list[str]) -> list[Tile]:
    tiles = []
    for tile in TILES:
        if tile.name in names:
            tiles.append(tile)
    return tiles


def all_tiles():
    return TILES
